# Generated by Django 4.2.30 on 2026-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='translation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
    ]
