# Generated by Django 4.2.30 on 2026-05-30 07:18

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=apps.accounts.models._referral_code, max_length=10, unique=True),
        ),
    ]
