# Generated by Django 4.2.30 on 2026-06-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userfollow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userfollow',
            new_name='accounts_us_followi_a56db0_idx',
            old_name='accounts_us_followi_idx',
        ),
    ]
