# Generated by Django 4.2.30 on 2026-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
