# Generated by Django 4.2.30 on 2026-06-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categorysubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categorysubscription',
            new_name='categories__categor_3971f3_idx',
            old_name='categories__categor_idx',
        ),
    ]
