# Generated by Django 4.2.30 on 2026-05-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='locations/icons/'),
        ),
    ]
