# Generated by Django 4.2.30 on 2026-05-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='interest',
            name='title_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
