# Generated by Django 4.2.30 on 2026-06-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_eventreminder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventreminder',
            new_name='attendance__remind__d22d30_idx',
            old_name='attendance__remind__idx',
        ),
    ]
